services:
  acropolis:
    build: .
    container_name: acropolis-bot
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: acropolis-nginx
    restart: always
    network_mode: host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
